version: "3.8"
services:
  riotpot:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: riotpot:latest
    restart: always
    ports:
      - 22:22
      - 23:23
      - 8080:8080
    env_file:
    - ./env./env.prod



