---
version: 1
type: template
# RiotPot configuration file.
# This file can be used as a template for further implementations and as a record of
# documentation for internal structure when in doubt on usage.

# 50 characters minimum long RANDOM string used to generate cryptographic signatures.
secret: 

riotpot:
  # If this boolean is set to a falsy value then `start` must be filled with the
  # list of services desired to be loaded and run at start, and `emulators` with
  # the list of available services to the app.
  autod: false
  local_build_on: 1

  # The name of the services is the name of the folder in which the plugin
  # is stored, inside the `pkg/` folder.
  # Example:
  #   * if the plugin is stored in: `pkg/telnetd`
  #   * then place: `- telnetd`

  # mode of operation allowed for Riotpot run
  allowed_modes:
    - low
    - high
    - hybrid

  # Contains a list of available services in the application.
  # This gives the user the ability to navigate or load
  # just the emulators that appear in this list, wether or not
  # the emulator plugin appears in the binary.
  #
  # Add here the emulator plugins you have included on the binary.
  emulators:
    - httpd
    - echod
    - sshd
    - telnetd
    - mqttd
    - coapd
    - modbusd

  # enter the name of the image comma separated by it's docker registry name
  # seprated by it's ip address, IP addresses should be in range 10.5.0.10-10.5.0.20
  # and unique for each container image name
  images:
    - mqtt, eclipse-mosquitto, 10.5.0.10
    - http, httpd, 10.5.0.12
    # - modbus, oitc/modbus-server, 10.5.0.11

  # `start` contains a list of services desired to be run
  # on-start variable used in Riotpot core on runtime only!
  start:

# Following block is setup for the user in case they want to configure which plugin/contianer
# to run upon starting of Riotpot core bypassing the manual interactive mode
##################################################################################################
  #Services which will run at start. For all the services, set `autod` to `true`.
  # enter them separated by space
  boot_plugins: httpd echod telnetd mqttd coapd modbusd
  
  # enter the name of the docker images which need to run at Riotpot
  start_images: mqtt http

  # Fill the mode, low, high or hybrid, to be used in containerized mode only
  mode: low
##################################################################################################

# The `databases` object contains a number of object defined database
# connection information. As the name indicates, `default` will be the default
# database used to store logs, binary entries, etc.
databases:
  - identity: 
    # Name of the targeted database
    dbname: mongodb
    # RiotPot only supports `mongodb` currently.
    engine: mongodb
    # IP or container name in the same network.
    host: localhost
    # Connection port to the database host.
    port: 27017
    # User and password to access the database.
    # NOTE: Do not hard-code the values in this file. Please do make
    # use of `.env` file for this purpose in production.
    username: superuser
    password: password
